//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Ladder.rc
//
#define IDS_STRING_INVALIDCONNECTION    1
#define IDS_ERROR_LOADING_BITMAP        2
#define IDS_SECON_10                    3
#define IDS_STRING_TIMER_MOD            4
#define IDS_STRING_COUNTER_MOD          5
#define IDS_STRING_REFERENCE            6
#define IDS_STRING_MEMORY_MOD           7
#define IDS_STRING_INPUTREGISTER_MOD    8
#define IDS_STRING_OUTPUTREGISTER_MOD   9
#define IDS_STRING_INITIALVALUE_MOD     10
#define IDS_STRING_ANALOGKANAL_MOD      11
#define IDS_STRING_ANALOGGIRIS_MOD      12
#define IDS_STRING_ANALOGCIKIS_MOD      13
#define IDS_STRING_TIMERS               14
#define IDS_STRING_COUNTERS             15
#define IDS_STRING_MEMORIES             16
#define IDS_STRING_INPUTS               17
#define IDS_STRING_OUTPUTS              18
#define IDS_STRING_BITS                 19
#define IDS_STRING_ANALOG_INPUTS        20
#define IDS_STRING_ANALOG_OUTPUTS       21
#define IDS_STRING_OUTPUT               22
#define IDS_STRING_BIT                  23
#define IDS_STRING_MEMORY               24
#define IDS_STRING_TIMER                25
#define IDS_STRING_COUNTER              26
#define IDS_STRING_INPUT                27
#define IDS_STRING_BLOCK                28
#define IDS_STRING_FUNCTION             29
#define IDS_STRING_LIST                 30
#define IDS_STRING_ELEMENT_INFO         31
#define IDS_STRING_COUNTER_LC           32
#define IDS_STRING_BLOCK_LC             33
#define IDS_STRING_FUNCTION_LC          34
#define IDS_STRING_INPUT_LC             35
#define IDS_STRING_BIT_LC               36
#define IDS_STRING_MEMORY_LC            37
#define IDS_STRING_LIST_LC              38
#define IDS_STRING_OUTPUT_LC            39
#define IDS_STRING_TIMER_LC             40
#define IDS_STRING_TEN_MULTIPLY         41
#define IDS_STRING_TAG_LADDERELEMENT    42
#define IDS_STRING_TAG_TYPE             43
#define IDS_STRING_TAG_KEY              44
#define IDS_STRING_TAG_NAME             45
#define IDS_STRING_TAG_REFERENCE        46
#define IDS_STRING_TAG_GRAPHIC          47
#define IDS_STRING_TAG_SUBNET_          48
#define IDS_STRING_TAG_LADDERELEMENTCOUNT 49
#define IDS_STRING_TAG_CENTER           50
#define IDS_STRING_TAG_INPUT            51
#define IDS_STRING_TAG_OUTPUT           52
#define IDS_STRING_TAG_REGISTER         53
#define IDS_STRING_TAG_CONNECTION_ELEMENT 54
#define IDS_STRING_TAG_ELEMENT_ID       55
#define IDS_STRING_TAG_ACTIVESUBNETKEY  56
#define IDS_STRING_TAG_SUBNET_COUNT     57
#define IDS_STRING_TAG_CONTEX           58
#define IDS_STRING_TAG_CNTPREPAS        59
#define IDS_STRING_TAG_CONNECTION_STILL 60
#define IDS_STRING_TAG_ELEMENT_TYPE     61
#define IDS_STRING_TAG_NETWORK_COLLECTION_COUNT 62
#define IDS_STRING_TAG_ID               63
#define IDS_STRING_TAG_CONNECTION_ELEMENT_COUNT 64
#define IDS_STRING_TAG_SUB_TYPE         65
#define IDD_DIALOG_ELEMENTINFO          143
#define IDC_EDIT_ID                     1000
#define IDC_EDIT_TYPE                   1001
#define IDC_LIST_PREELIST               1002
#define IDC_LIST_PASSLIST               1003
#define IDC_EDIT_NAME                   1004
#define IDC_RADIO_PRE0                  1005
#define IDC_EDIT_REGISTERBIT            1005
#define IDC_EDIT_SET_ELEMENT            1005
#define IDC_RADIO_CENTER0               1006
#define IDC_EDIT_RESET_ELEMENT          1006
#define IDC_RADIO_PAST0                 1007
#define IDC_EDIT_ID1                    1008
#define IDC_BUTTON_SET                  1008
#define IDC_RADIO_PRE1                  1009
#define IDC_RADIO_CENTER1               1010
#define IDC_RADIO_PAST1                 1011
#define IDC_EDIT_NAME0                  1012
#define IDC_EDIT_NAME1                  1013
#define IDC_RADIO_SET0                  1014
#define IDC_RADIO_P1_0                  1015
#define IDC_RADIO_SET1                  1016
#define IDC_RADIO_RESET1                1017
#define IDC_RADIO_RESET0                1018
#define IDC_RADIO_P2_0                  1019
#define IDC_RADIO_P3_0                  1020
#define IDC_RADIO_P4_0                  1021
#define IDC_RADIO_P5_0                  1022
#define IDC_RADIO_P6_0                  1023
#define IDC_RADIO_P1_1                  1024
#define IDC_RADIO_P2_1                  1025
#define IDC_RADIO_P3_1                  1026
#define IDC_RADIO_P4_1                  1027
#define IDC_RADIO_P5_1                  1028
#define IDC_RADIO_P6_1                  1029
#define IDC_EDIT_CONECTIONID            1103
#define IDC_EDIT_ID0                    1104
#define IDD_DIALOG_CONNECTIONINFO       9000
#define IDC_BUTTON_SIGNAL               9000
#define IDD_DIALOG_NAME                 9001
#define IDC_EDIT_SIGNAL                 9001
#define IDB_BITMAP_ELEMENT_LISTE        9002
#define IDC_STATIC_IR00                 9002
#define IDC_BUTTON_SIGNAL2              9003
#define IDC_STATIC_IR1                  9004
#define IDC_COMBO_IR00                  9005
#define IDC_BUTTON_ELEMENT0             9006
#define IDC_COMBO_REFERENCE             9006
#define IDC_BUTTON_ELEMENT1             9007
#define IDC_STATIC_COLOR_WND            9007
#define IDC_STATIC_CONNECTIONBILD       9008
#define IDC_BUTTON_GSS                  9009
#define IDC_CHECK_FACTOROUT             9010
#define IDC_COMBO_CONNECTIONSTILL       9011
#define IDR_LADDER                      9012
#define IDR_LDR                         9013
#define IDB_BITMAP_CONNECTIONBILD       9014
#define IDC_RADIO_CONTACTOR_NET         9014
#define IDC_RADIO_TIMER_NET             9015
#define IDC_COMBO_NAME                  9015
#define IDC_RADIO_COUNTER_NET           9016
#define IDC_STATIC_SET                  9017
#define IDC_STATIC_RESET                9018
#define IDB_BITMAP_OUTPUT               9019
#define IDC_EDIT_OPERANDEN_A            9020
#define IDC_STATIC_OPERANDEN_A          9021
#define IDC_COMBO_MODE                  9022
#define IDC_LIST_USED                   9023
#define IDC_EDIT_OPERANDEN_B            9023
#define IDC_COMBO1                      9024
#define IDC_COMBO_SUB_MODE              9024
#define IDC_STATIC_OPERANDEN_B          9024
#define IDC_EDIT_TA                     9025
#define IDC_COMBO2                      9025
#define IDC_EDIT_TB                     9026
#define IDC_BUTTON_SYMBOL_ADD           9027
#define IDC_BUTTON_SYMBOL_DELETE        9028
#define IDC_LIST_AVAILABLE              9029
#define IDC_BUTTON_UPDATE_SYMBOL        9030
#define IDC_EDIT_COMMENT_LINE           9031
#define IDC_EDIT_EXPLNTN                9031
#define IDD_DIALOG_SUBNET_SELECTION     9032
#define IDB_BITMAP_MEMORY_R             9033
#define IDB_BITMAP_MEMORY_S             9034
#define IDB_BITMAP_TIMER_R              9035
#define IDB_BITMAP_TIMER_S              9036
#define IDB_BITMAP_COUNTER_R            9037
#define IDB_BITMAP_COUNTER_S            9038
#define IDB_BITMAP_BIT                  9039
#define IDB_BITMAP_MEMORY               9040
#define IDB_BITMAP_TIMER_MODE_00        9042
#define IDB_BITMAP_TIMER_MODE_01        9043
#define IDB_BITMAP_TIMER_MODE_02        9044
#define IDB_BITMAP_TIMER_MODE_03        9045
#define IDB_BITMAP_TIMER_MODE_04        9046
#define IDB_BITMAP_TIMER_MODE_05        9047
#define IDB_BITMAP_TIMER_MODE_06        9048
#define IDB_BITMAP_TIMER_MODE_07        9049
#define IDC_RADI_O4                     9050
#define IDC_STATIC_TB                   9050
#define IDC_RADI_O5                     9051
#define IDC_STATIC_ELEMENT              9051
#define IDC_RADI_O6                     9052
#define IDC_STATIC_REGBIT               9052
#define IDC_RADI_O7                     9053
#define IDC_BUTTON_BROWSE_A             9053
#define IDC_RADI_O8                     9054
#define IDC_BUTTON_BROWSE_B             9054
#define IDC_RADI_O9                     9055
#define IDC_BUTTON1                     9055
#define IDC_BUTTON_BROWSE_SYMBOL        9055
#define IDC_BUTTON_I_VAL_SET            9055
#define IDB_BITMAP_TIMER                9056
#define IDC_RADIO_10                    9056
#define IDC_BUTTON_BROWSE_SYMBOL2       9056
#define IDB_BITMAP_COUNTER              9057
#define IDC_RADIO_11                    9057
#define IDC_CHECK_DOLISTING             9057
#define IDD_DIALOG_TIMERS               9058
#define IDC_RADIO_12                    9058
#define IDC_EDIT_INITIAL_VALUE          9058
#define IDB_BITMAP_CONTACTOR            9059
#define IDC_RADIO_13                    9059
#define IDC_BUTTON_EEPROM_TA            9059
#define IDB_BITMAP_INVERTED_CONTACTOR   9060
#define IDC_RADIO_14                    9060
#define IDC_BUTTON_EEPROM_TB            9060
#define IDB_BITMAP_OUTPUT_CONTACTOR     9061
#define IDC_RADI_O10                    9061
#define IDC_RADI_15                     9061
#define IDB_BITMAP_CONNECTION           9062
#define IDC_RADI_O11                    9062
#define IDC_RADI_16                     9062
#define IDC_EDIT_EEPROM_TA              9062
#define IDB_BITMAP_COUNTER_00           9063
#define IDC_RADI_O12                    9063
#define IDC_RADI_17                     9063
#define IDC_EDIT_EEPROM_TB              9063
#define IDB_BITMAP_COUNTER_01           9064
#define IDC_RADI_18                     9064
#define IDC_CHECK_TA                    9064
#define IDB_BITMAP_COUNTER_02           9065
#define IDC_RADI_19                     9065
#define IDC_CHECK_TB                    9065
#define IDB_BITMAP_COUNTER_03           9066
#define IDC_RADI_20                     9066
#define IDC_LIST_EPROM_WORD             9067
#define IDC_RADIO_20                    9067
#define IDB_MEMORY_MODE_00              9068
#define IDC_EDIT1                       9068
#define IDB_MEMORY_MODE_01              9069
#define IDC_EDIT3                       9069
#define IDB_MEMORY_MODE_02              9070
#define IDC_LIST1                       9070
#define IDB_MEMORY_MODE_03              9071
#define IDC_LIST2                       9071
#define IDB_MEMORY_MODE_04              9072
#define IDC_LIST3                       9072
#define IDB_MEMORY_MODE_05              9073
#define IDC_LIST4                       9073
#define IDB_MEMORY_MODE_06              9074
#define IDC_EDIT2                       9074
#define IDB_MEMORY_MODE_07              9075
#define IDC_LIST_EPROM_BYTE             9076
#define IDC_BUTTON_REMOVEBYTE           9077
#define IDC_LIST_EPROM_WORDS            9078
#define IDB_BITMAP_TIMER_DUMY           9079
#define IDC_LIST_BYTES                  9079
#define IDC_RADI_O1                     9080
#define IDC_COMBO_VOLUME                9080
#define IDC_RADI_O2                     9081
#define IDC_LIST_WORDS                  9081
#define IDC_STATIC_MOD                  9082
#define IDC_BUTTON_REMOVE_WORD          9082
#define IDC_RADI_O3                     9083
#define IDC_EDIT_INITIAL_VALUE_WORD     9083
#define IDC_STATIC_TA                   9084
#define IDC_BUTTON_WORD_VAL_SET         9084
#define IDR_LD                          9085
#define IDD_DIALOG_TEST                 9086
#define IDD_DIALOG_SNC                  9087
#define IDD_DIALOG_MEMORIES             9088
#define IDD_DIALOG_DIGITALINPUTS        9089
#define IDB_BITMAP_BLOCK                9090
#define IDD_DIALOG_DIGITALOUTPUTS       9090
#define IDB_BITMAP_FUNCTION             9091
#define IDB_BITMAP_ILIST                9092
#define IDD_DIALOG_EEPROM               9094
#define IDD_DIALOG_COUNTERS             9096
#define IDD_DIALOG_BITS                 9097
#define IDD_DIALOG_ANALOGINPUTS         9098
#define IDD_DIALOG_ANALOGOUTPUTS        9099
#define IDB_BITMAP_FUNCTION_00          9100
#define IDB_BITMAP_FUNCTION_01          9101
#define IDB_BITMAP_FUNCTION_02          9102
#define IDB_BITMAP_FUNCTION_03          9103
#define IDB_BITMAP_FUNCTION_04          9104
#define IDB_BITMAP_FUNCTION_05          9105
#define IDB_BITMAP_AI00                 9105
#define IDB_BITMAP_FUNCTION_06          9106
#define IDB_BITMAP_AI01                 9106
#define IDB_BITMAP_FUNCTION_07          9107
#define IDB_BITMAP_AI02                 9107
#define IDB_BITMAP_FUNCTION_08          9108
#define IDB_BITMAP_AI03                 9108
#define IDB_BITMAP_FUNCTION_09          9109
#define IDB_BITMAP_AI04                 9109
#define IDB_BITMAP_FUNCTION_10          9110
#define IDB_BITMAP_AI05                 9110
#define IDB_BITMAP_FUNCTION_11          9111
#define IDB_BITMAP_AI06                 9111
#define IDB_BITMAP_FUNCTION_12          9112
#define IDB_BITMAP_AI07                 9112
#define IDB_BITMAP_FUNCTION_13          9113
#define IDB_BITMAP_AO00                 9113
#define IDB_BITMAP_FUNCTION_14          9114
#define IDB_BITMAP_AO01                 9114
#define IDB_BITMAP_FUNCTION_15          9115
#define IDB_BITMAP_AO02                 9115
#define IDB_BITMAP_FUNCTION_16          9116
#define IDB_BITMAP_AO03                 9116
#define IDB_BITMAP_FUNCTION_17          9117
#define IDB_BITMAP_AO04                 9117
#define IDB_BITMAP_FUNCTION_18          9118
#define IDB_BITMAP_AO05                 9118
#define IDB_BITMAP_FUNCTION_19          9119
#define IDB_BITMAP_AO06                 9119
#define IDB_BITMAP_FUNCTION_20          9120
#define IDB_BITMAP_AO07                 9120
#define IDB_BITMAP_FUNCTION_21          9121
#define IDD_DIALOG_ELEMENTINFO_TEXT     9121
#define IDB_BITMAP_FUNCTION_22          9122
#define IDB_BITMAP_SUBROUTINE           9122
#define IDB_BITMAP_FUNCTION_23          9123
#define IDD_DIALOG_REGISTERS            9123
#define IDB_BITMAP_FUNCTION_24          9124
#define IDB_BITMAP_FUNCTION_25          9125
#define IDD_DIALOG_EBYTES               9126
#define IDD_DIALOG_EWORDS               9127
#define IDD_DIALOG_BYTES                9128
#define IDB_BITMAP1                     9130
#define IDD_DIALOG_WORDS                9134
#define IDB_BITMAP_IR00                 9203
#define IDB_BITMAP_IR00_0               9204
#define IDB_BITMAP_IR00_1               9205
#define IDB_BITMAP_IR00_2               9206
#define IDB_BITMAP_IR00_3               9207
#define IDB_BITMAP_IR00_4               9208
#define IDB_BITMAP_IR00_5               9209
#define IDB_BITMAP_IR00_6               9210
#define IDB_BITMAP_IR00_7               9211
#define IDB_BITMAP_IR00_8               9212
#define IDB_BITMAP_IR00_9               9213
#define IDB_BITMAP_OR00                 9322
#define IDB_BITMAP_OR00_0               9323
#define IDB_BITMAP_OR00_1               9324
#define IDB_BITMAP_OR00_2               9325
#define IDB_BITMAP_OR00_3               9326
#define IDB_BITMAP_OR00_4               9327
#define IDB_BITMAP_OR00_5               9328
#define IDB_BITMAP_OR00_6               9329
#define IDB_BITMAP_OR00_7               9330
#define IDB_BITMAP_OR00_8               9331
#define IDB_BITMAP_OR00_9               9332
#define IDB_BITMAP_OR00_10              9333
#define IDB_BITMAP_OR00_11              9334
#define IDC_LIST_EEPROM_BYTE            9335

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        9136
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         9085
#define _APS_NEXT_SYMED_VALUE           9086
#endif
#endif
